### ISSUE TITLE
libc-TODOs

### ISSUE THREAD

**Issue by zatkh** [marnovandermaas/riscv-isa-sim#1]
1.some spike dependent functions to implement for example using pk like the following.

extern "C" {
    void riscv_poweroff(int status){
        pk::htif_poweroff();
    }
    void riscv_write(const char* s, unsigned int length) {
        util::putstring(s, `length);`
    }
    unsigned long long riscv_clock_monotonic() {
        volatile unsigned long* tmp = (volatile unsigned long*)config::mtime;
        return (unsigned long long) *tmp;
    }
}

**Comment by marnovandermaas** [comment]
@zatkh I already have a kind of cheat to shut down the simulator by writing to the following configuration status register: CSR_BAREMETALEXIT   0x405
