### ISSUE TITLE
Add support for UART

### ISSUE THREAD

**Issue by marnovandermaas** [marnovandermaas/riscv-isa-sim#3]
XV6 expects there to be a UART at memory address: 0x1000 0000, which is currently not there in Spike.

**Comment by zatkh** [comment]
yeah that's a problem on spike for example FreeRTOS on spike just abstract that[1].

[1]https://github.com/illustris/FreeRTOS-RISCV/issues/11

**Comment by marnovandermaas** [comment]
I modified XV6 to do UART over the tohost and fromhost interface of Spike. This way we do not need a memory mapped UART.

For more details on the fix see:
https://github.com/marnovandermaas/xv6-riscv/tree/1102daa96aeb3a80938450baad8871f1d5d45125
